#Eva Françoise Sansano Larrea 51238758W
OPTS = -Wall -O3 -std=c++0x

all: maze_bt

maze_bt: maze_bt.cc
	g++ ${OPTS} -o maze_bt maze_bt.cc 2>/dev/null

tar: maze_bt.cc makefile
	tar cvfz 51238758W.tar.gz maze_bt.cc makefile

clean: 
	rm -f maze_bt 51238758W.tar.gz
 
